### ISSUE TITLE
RP0.dll causes EditorExtensionRedux X/C shortcuts to stop working when entering VAB/SPH

### ISSUE THREAD

**Issue by mateusviccari** [KSP-RO/RP-1#2061]
Every time I enter VAB, I have to press the "Reset mode and snap keys" button from Editor Extensions Redux icon for the X/C shortcuts to work. I noticed that this problem goes away if I remove the RP0.dll from the plugins folder. Somehow, it is messing with that mod's shortcuts.

**Comment by arrowmaster** [comment]
Probably already fixed by https://github.com/KSP-RO/RP-1/commit/340901b9f6470ecca7908f16cd64813253a3734d.

You'll need to wait for the next RP-1 release.

**Comment by linuxgurugamer** [comment]
@arrowmaster I looked at that.  Was the Harmony patching fixing a KSP bug, or just the issue with EEX?  The EEX fix I put in was somewhat of a hack (as I assume you know), I still don't know why the values are being set to null, but checking for them does seem to solve the problem.

**Comment by arrowmaster** [comment]
@linuxgurugamer You will have to ask @NathanKell for more info but I think it was just trying to fix the EEX bug.

**Comment by NathanKell** [comment]
@linuxgurugamer the issue is that EEX nukes KSP's snap and symmetry hotkeys. It does so during start here (https://github.com/linuxgurugamer/EditorExtensionsRedux/blob/master/EditorExtensionsRedux/EditorExtensionsRedux.cs#L776 ) and whenever 'reset hotkeys' is pressed (see here https://github.com/linuxgurugamer/EditorExtensionsRedux/blob/74529ccc1058a32a9dcb1fa10f541171f188d8f6/EditorExtensionsRedux/SettingsWindow.cs#L227-L243 for that logic). Note that settings.cfg is saved prior to nuking, which means that--at the time reset is pressed--settings.cfg on disk is correct.

All this means that, once EEX starts (and/or once the reset button is pressed), the hotkeys in KSP's settings will be null. That means that if the player ever does something that causes KSP's settings to be saved (they go into the settings menu, for example), those empty keybinds will be saved to settings.cfg, and the next time EEX starts, it will pull from settings and realize those keybinds are null. Your temp fix is a workaround to this situation: if EEX does ever encounter such a situation, it will manually run the reset logic (at the cost of losing whatever keybinds the player did want for snap and symmetry).

I believe this design choice was done because: EEX needs KSP to not do its default behavior when the snap or symmetry keys are pressed. But rather than making KSP not do its default behavior, or stomp on it with EEX's state, or anything else, the choice was made to simply cause KSP to stop listening to those keys itself--and to do so by nuking their keybinds.
A solution that would not require any of this setting-resetting logic would be to prevent KSP from responding to the keypresses, though that would presumably require Harmony; failing that, you could let KSP respond, and then a frame later clobber the symmetry and snap state with your own based on storing your own state (i.e. let KSP act, but then override it).
Or you could leave things as they are, since my guess is not too many people actually change their snap and symmetry keybinds, so it most cases your existing bandaid will be transparent to the user and they will no longer notice the problem.

In the code I had in RP-1, that just got removed, I used Harmony to get around this problem a third way (since I couldn't touch EEX directly): I wrote EEX's keybinds into settings.cfg at write time, and restored EEX's binds from settings.cfg at load time, but after doing so cleared KSP's binds. That's another way to solve the issue with harmony without risking settings.cfg storing null keybinds, but it again is a bit messy since it makes KSP _think_ those keys aren't bound (like in the current EEX approach).

**Comment by linuxgurugamer** [comment]
yes, but how does someone get into the settings while in the Editor, which is the only time that EEX is active?

Only thing I can think of, since you can't get into the settings in the editor, is if another mod writes the settings out.  If that's the case, then I can add a GameEvent to catch the OnGameSettingsWritten and then update the values, write them  out again, then reset them to what EEX needs.

I'd still leave the recent code in, but this would fix the problem.  Other than RP1, are you aware of any mod which might write the settings while in the editor?

Would you be willing to test this for me?  While I'll still leave the hack mentioned above in, it _does_ write to the log file if it detects the issue, so would be easy to see if it's actually fixed.

Regarding the keys themselves, I've never had anyone complain about the patch I put in a few years ago to reset the keys setting the values back to X and C, so I'm not too concerned about it.  But would be nice to have the real fix in, I don't particularly like the hack since it was done as a workaround.

Also, thank you for the explanation

**Comment by linuxgurugamer** [comment]
I actually found that when you go into the engineer report and change what's shown, that it actually writes the settings file, was able to use that to test it.

This is a debug build of EEX, just replace the existing one:

https://www.dropbox.com/t/iLbBX8z7UgjwPYnC

There are some additional messages in the log which will say when the setting sfile is being resaved

**Comment by NathanKell** [comment]
Ah, dang, yeah, that makes sense. What I get for not actually doing an ILSpy analyze on WriteCfg before assuming it didn't get written to in editor.

**Comment by linuxgurugamer** [comment]
EX Version 3.4.5 has the final fix for the issue

**Comment by NathanKell** [comment]
Woohoo! Cheers, lgg! :)
